const express = require('express')
const router = express.Router()
const userController = require('../controllers/UserController')
const { authMiddleWare, authUserMiddleWare } = require('../middleware/authMiddleware')
const dotenv = require('dotenv')
dotenv.config()

router.post('/sign-up', userController.createUser)
router.post('/send-otp', userController.sendOtp)
router.delete('/delete-otp/:id', userController.deleteOtp)
router.put('/reset-password', userController.userResetPassword)
router.put('/change-password', userController.changePassword)
router.post('/sign-in', userController.loginUser)
router.post('/log-out', userController.logoutUser)
router.put('/update-user/:id', authUserMiddleWare, userController.updateUser)
router.delete('/delete-user/:id', authMiddleWare, userController.deleteUser)
router.get('/getAll', authMiddleWare, userController.getAllUser)
router.get('/get-details/:id', authUserMiddleWare, userController.getDetailsUser)
router.post('/refresh-token', userController.refreshToken)

module.exports = router
